name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobra das contribuições
        uses: Platane/snk@v3
        with:
          github_user_name: PedroBrazz
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Fazer commit da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: "gerar animação da cobra"
          add: "dist/snake.svg dist/snake-dark.svg"
